// Code generated by cmd/generate. DO NOT EDIT.

package tools

import (
	"context"
	"encoding/json"
	"math"

	"github.com/mark3labs/mcp-go/mcp"
	mcpserver "github.com/mark3labs/mcp-go/server"

	"github.com/mac-lucky/pushward-mcp/internal/client"
)

func registerAPITools(s *mcpserver.MCPServer, api *client.APIClient) {

	// create_activity
	s.AddTool(
		mcp.NewTool("create_activity",
			mcp.WithDescription("Create activity"),
			mcp.WithNumber("ended_ttl",
				mcp.Description("Seconds after ENDED before auto-delete (1s to 30 days) (min: 1, max: 2.592e+06)"),
			),
			mcp.WithString("name",
				mcp.Required(),
				mcp.Description("Human-readable activity name"),
			),
			mcp.WithNumber("priority",
				mcp.Description("Eviction priority (0=lowest, 10=highest, default 0) (min: 0, max: 10)"),
			),
			mcp.WithString("slug",
				mcp.Required(),
				mcp.Description("Unique activity identifier (alphanumeric, hyphens, underscores)"),
			),
			mcp.WithNumber("stale_ttl",
				mcp.Description("Seconds of inactivity before auto-ending (1s to 30 days) (min: 1, max: 2.592e+06)"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleCreateActivity(ctx, req, api)
		},
	)

	// create_notification
	s.AddTool(
		mcp.NewTool("create_notification",
			mcp.WithDescription("Create notification"),
			mcp.WithArray("actions",
				mcp.Description("Server-driven action buttons. Max 10 (Apple cap)."),
				mcp.Items(map[string]any{"type": "object"}),
			),
			mcp.WithString("activity_slug",
				mcp.Description("activity_slug"),
			),
			mcp.WithString("body",
				mcp.Required(),
				mcp.Description("Notification body"),
			),
			mcp.WithString("collapse_id",
				mcp.Description("Collapse ID for replacing notifications"),
			),
			mcp.WithString("icon_url",
				mcp.Description("http or https URL for per-notification source avatar, shown as the Communication Notification avatar on iOS. Recommended ≤256×256 and ≤100 KB; responses larger than 512 KB are rejected by the iOS extension to protect the 24 MB memory budget."),
			),
			mcp.WithString("level",
				mcp.Description("Interruption level (default: active)"),
				mcp.Enum("passive", "active", "time-sensitive", "critical"),
			),
			mcp.WithObject("media",
				mcp.Description("Rich media attachment (image, video, or audio). HTTPS only."),
			),
			mcp.WithBoolean("push",
				mcp.Description("Send as an APNs push to the user's devices. Defaults to true; set false to store in the inbox only."),
			),
			mcp.WithString("source",
				mcp.Description("Source identifier"),
			),
			mcp.WithString("source_display_name",
				mcp.Description("Human-readable source name"),
			),
			mcp.WithString("subtitle",
				mcp.Description("Notification subtitle"),
			),
			mcp.WithString("thread_id",
				mcp.Description("Thread identifier for grouping"),
			),
			mcp.WithString("title",
				mcp.Required(),
				mcp.Description("Notification title"),
			),
			mcp.WithString("url",
				mcp.Description("Action URL"),
			),
			mcp.WithNumber("volume",
				mcp.Description("Volume for critical alerts (0.0-1.0) (min: 0, max: 1)"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleCreateNotification(ctx, req, api)
		},
	)

	// create_widget
	s.AddTool(
		mcp.NewTool("create_widget",
			mcp.WithDescription("Create widget"),
			mcp.WithString("name",
				mcp.Required(),
				mcp.Description("Human-readable widget name shown in the iOS configuration picker."),
			),
			mcp.WithNumber("push_throttle",
				mcp.Description("Per-widget minimum seconds between pushes. (min: 1, max: 3600)"),
			),
			mcp.WithString("slug",
				mcp.Required(),
				mcp.Description("Unique widget identifier (alphanumeric, hyphens, underscores). Per-user namespace separate from activity slugs."),
			),
			mcp.WithString("content_json",
				mcp.Required(),
				mcp.Description("Activity content as JSON object. PATCH endpoints apply RFC 7396 JSON Merge Patch semantics — only send the fields you want to change, null clears a field, absent preserves. Fields: template (generic|countdown|steps|alert|gauge|timeline), progress (0.0-1.0), state, icon, subtitle, accent_color, background_color, text_color. Template-specific: countdown (duration as integer seconds (60) or duration string (\"60s\", \"1h30m\"), end_date [unix timestamp], warning_threshold, completion_message, alarm, snooze_seconds (60-3600, default 300; how far the /snooze action and iOS AlarmKit snooze extend the timer, only with alarm); if both duration and end_date are sent, end_date wins), steps (current_step, total_steps, step_labels), alert (severity: critical|warning|info, fired_at), gauge (value, min_value, max_value, unit), timeline (value as {key:number}, history as {key:[{timestamp,value}]}, scale, thresholds)."),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleCreateWidget(ctx, req, api)
		},
	)

	// delete_activity
	s.AddTool(
		mcp.NewTool("delete_activity",
			mcp.WithDescription("Delete activity"),
			mcp.WithString("slug",
				mcp.Required(),
				mcp.Description("slug path parameter"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleDeleteActivity(ctx, req, api)
		},
	)

	// delete_widget
	s.AddTool(
		mcp.NewTool("delete_widget",
			mcp.WithDescription("Delete widget"),
			mcp.WithString("slug",
				mcp.Required(),
				mcp.Description("slug path parameter"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleDeleteWidget(ctx, req, api)
		},
	)

	// get_activity
	s.AddTool(
		mcp.NewTool("get_activity",
			mcp.WithDescription("Get activity"),
			mcp.WithString("slug",
				mcp.Required(),
				mcp.Description("slug path parameter"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleGetActivity(ctx, req, api)
		},
	)

	// get_health
	s.AddTool(
		mcp.NewTool("get_health",
			mcp.WithDescription("Health check"),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleGetHealth(ctx, req, api)
		},
	)

	// get_me
	s.AddTool(
		mcp.NewTool("get_me",
			mcp.WithDescription("Get current user profile"),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleGetMe(ctx, req, api)
		},
	)

	// get_widget
	s.AddTool(
		mcp.NewTool("get_widget",
			mcp.WithDescription("Get widget"),
			mcp.WithString("slug",
				mcp.Required(),
				mcp.Description("slug path parameter"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleGetWidget(ctx, req, api)
		},
	)

	// list_widgets
	s.AddTool(
		mcp.NewTool("list_widgets",
			mcp.WithDescription("List widgets"),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleListWidgets(ctx, req, api)
		},
	)

	// update_activity
	s.AddTool(
		mcp.NewTool("update_activity",
			mcp.WithDescription("Update activity"),
			mcp.WithString("slug",
				mcp.Required(),
				mcp.Description("slug path parameter"),
			),
			mcp.WithNumber("priority",
				mcp.Description("priority"),
			),
			mcp.WithString("sound",
				mcp.Description("Optional Live Activity alert sound. 'default' uses the iOS system sound; other values must match a bundled sound."),
				mcp.Enum("default", "chime", "alert", "success", "warning", "bell", "ding", "buzz", "notification"),
			),
			mcp.WithString("state",
				mcp.Description("Target state. Accepts ongoing or ended (case-insensitive). Optional — if omitted, the current stored state is kept. Setting ended on an ongoing activity dismisses the Live Activity."),
			),
			mcp.WithString("content_json",
				mcp.Required(),
				mcp.Description("Activity content as JSON object. PATCH endpoints apply RFC 7396 JSON Merge Patch semantics — only send the fields you want to change, null clears a field, absent preserves. Fields: template (generic|countdown|steps|alert|gauge|timeline), progress (0.0-1.0), state, icon, subtitle, accent_color, background_color, text_color. Template-specific: countdown (duration as integer seconds (60) or duration string (\"60s\", \"1h30m\"), end_date [unix timestamp], warning_threshold, completion_message, alarm, snooze_seconds (60-3600, default 300; how far the /snooze action and iOS AlarmKit snooze extend the timer, only with alarm); if both duration and end_date are sent, end_date wins), steps (current_step, total_steps, step_labels), alert (severity: critical|warning|info, fired_at), gauge (value, min_value, max_value, unit), timeline (value as {key:number}, history as {key:[{timestamp,value}]}, scale, thresholds)."),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleUpdateActivity(ctx, req, api)
		},
	)

	// update_widget
	s.AddTool(
		mcp.NewTool("update_widget",
			mcp.WithDescription("Update widget"),
			mcp.WithString("slug",
				mcp.Required(),
				mcp.Description("slug path parameter"),
			),
			mcp.WithString("name",
				mcp.Description("name"),
			),
			mcp.WithNumber("push_throttle",
				mcp.Description("push_throttle"),
			),
			mcp.WithString("content_json",
				mcp.Required(),
				mcp.Description("Activity content as JSON object. PATCH endpoints apply RFC 7396 JSON Merge Patch semantics — only send the fields you want to change, null clears a field, absent preserves. Fields: template (generic|countdown|steps|alert|gauge|timeline), progress (0.0-1.0), state, icon, subtitle, accent_color, background_color, text_color. Template-specific: countdown (duration as integer seconds (60) or duration string (\"60s\", \"1h30m\"), end_date [unix timestamp], warning_threshold, completion_message, alarm, snooze_seconds (60-3600, default 300; how far the /snooze action and iOS AlarmKit snooze extend the timer, only with alarm); if both duration and end_date are sent, end_date wins), steps (current_step, total_steps, step_labels), alert (severity: critical|warning|info, fired_at), gauge (value, min_value, max_value, unit), timeline (value as {key:number}, history as {key:[{timestamp,value}]}, scale, thresholds)."),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleUpdateWidget(ctx, req, api)
		},
	)
}

func handleCreateActivity(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	input := client.CreateActivityInput{
		Name: func() string { v, _ := req.RequireString("name"); return v }(),
		Slug: func() string { v, _ := req.RequireString("slug"); return v }(),
	}
	if v := req.GetFloat("ended_ttl", math.NaN()); !math.IsNaN(v) {
		input.EndedTTL = &v
	}
	if v := req.GetFloat("priority", math.NaN()); !math.IsNaN(v) {
		input.Priority = &v
	}
	if v := req.GetFloat("stale_ttl", math.NaN()); !math.IsNaN(v) {
		input.StaleTTL = &v
	}
	raw, err := api.CreateActivity(ctx, input)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleCreateNotification(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	input := client.CreateNotificationInput{
		Body:  func() string { v, _ := req.RequireString("body"); return v }(),
		Title: func() string { v, _ := req.RequireString("title"); return v }(),
	}
	if v, ok := req.GetArguments()["actions"]; ok && v != nil {
		buf, err := json.Marshal(v)
		if err != nil {
			return mcp.NewToolResultError("encoding actions: " + err.Error()), nil
		}
		// Forward opaque JSON — server is the source of truth for the
		// actions schema, so new fields don't require an MCP rebuild.
		input.Actions = json.RawMessage(buf)
	}
	if v := req.GetString("activity_slug", ""); v != "" {
		input.ActivitySlug = v
	}
	if v := req.GetString("collapse_id", ""); v != "" {
		input.CollapseID = v
	}
	if v := req.GetString("icon_url", ""); v != "" {
		input.IconURL = v
	}
	if v := req.GetString("level", ""); v != "" {
		input.Level = v
	}
	if v, ok := req.GetArguments()["media"]; ok && v != nil {
		buf, err := json.Marshal(v)
		if err != nil {
			return mcp.NewToolResultError("encoding media: " + err.Error()), nil
		}
		var parsed *client.MediaAttachment
		if err := json.Unmarshal(buf, &parsed); err != nil {
			return mcp.NewToolResultError("parsing media: " + err.Error()), nil
		}
		input.Media = parsed
	}
	input.Push = req.GetBool("push", false)
	if v := req.GetString("source", ""); v != "" {
		input.Source = v
	}
	if v := req.GetString("source_display_name", ""); v != "" {
		input.SourceDisplayName = v
	}
	if v := req.GetString("subtitle", ""); v != "" {
		input.Subtitle = v
	}
	if v := req.GetString("thread_id", ""); v != "" {
		input.ThreadID = v
	}
	if v := req.GetString("url", ""); v != "" {
		input.URL = v
	}
	if v := req.GetFloat("volume", math.NaN()); !math.IsNaN(v) {
		input.Volume = &v
	}
	raw, err := api.CreateNotification(ctx, input)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleCreateWidget(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	contentStr, err := req.RequireString("content_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(contentStr)) {
		return mcp.NewToolResultError("content_json is not valid JSON"), nil
	}
	paramName, err := req.RequireString("name")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	paramSlug, err := req.RequireString("slug")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	input := client.CreateWidgetInput{
		Name:    paramName,
		Slug:    paramSlug,
		Content: json.RawMessage(contentStr),
	}
	if v := req.GetFloat("push_throttle", math.NaN()); !math.IsNaN(v) {
		input.PushThrottle = &v
	}
	raw, err := api.CreateWidget(ctx, input)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleDeleteActivity(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	paramSlug, err := req.RequireString("slug")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	err = api.DeleteActivity(ctx, paramSlug)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText("deleted successfully"), nil
}

func handleDeleteWidget(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	paramSlug, err := req.RequireString("slug")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	err = api.DeleteWidget(ctx, paramSlug)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText("deleted successfully"), nil
}

func handleGetActivity(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	paramSlug, err := req.RequireString("slug")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	raw, err := api.GetActivity(ctx, paramSlug)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleGetHealth(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	raw, err := api.GetHealth(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleGetMe(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	raw, err := api.GetMe(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleGetWidget(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	paramSlug, err := req.RequireString("slug")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	raw, err := api.GetWidget(ctx, paramSlug)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleListWidgets(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	raw, err := api.ListWidgets(ctx)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleUpdateActivity(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	paramSlug, err := req.RequireString("slug")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	contentStr, err := req.RequireString("content_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(contentStr)) {
		return mcp.NewToolResultError("content_json is not valid JSON"), nil
	}
	input := client.UpdateActivityInput{
		Content: json.RawMessage(contentStr),
	}
	if v := req.GetFloat("priority", math.NaN()); !math.IsNaN(v) {
		input.Priority = &v
	}
	if v := req.GetString("sound", ""); v != "" {
		input.Sound = v
	}
	if v := req.GetString("state", ""); v != "" {
		input.State = v
	}
	raw, err := api.UpdateActivity(ctx, paramSlug, input)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleUpdateWidget(ctx context.Context, req mcp.CallToolRequest, api *client.APIClient) (*mcp.CallToolResult, error) {
	paramSlug, err := req.RequireString("slug")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	contentStr, err := req.RequireString("content_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(contentStr)) {
		return mcp.NewToolResultError("content_json is not valid JSON"), nil
	}
	input := client.UpdateWidgetInput{
		Content: json.RawMessage(contentStr),
	}
	if v := req.GetString("name", ""); v != "" {
		input.Name = v
	}
	if v := req.GetFloat("push_throttle", math.NaN()); !math.IsNaN(v) {
		input.PushThrottle = &v
	}
	raw, err := api.UpdateWidget(ctx, paramSlug, input)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}
