// Code generated by cmd/generate. DO NOT EDIT.

package tools

import (
	"context"
	"encoding/json"
	"math"

	"github.com/mark3labs/mcp-go/mcp"
	mcpserver "github.com/mark3labs/mcp-go/server"

	"github.com/mac-lucky/pushward-mcp/internal/client"
)

func registerRelayTools(s *mcpserver.MCPServer, relay *client.RelayClient) {

	// relay_argocd
	s.AddTool(
		mcp.NewTool("relay_argocd",
			mcp.WithDescription("Receive ArgoCD sync webhook"),
			mcp.WithString("app",
				mcp.Description("app"),
			),
			mcp.WithString("event",
				mcp.Description("event"),
			),
			mcp.WithString("repo_url",
				mcp.Description("repo_url"),
			),
			mcp.WithString("revision",
				mcp.Description("revision"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayArgocd(ctx, req, relay)
		},
	)

	// relay_backrest
	s.AddTool(
		mcp.NewTool("relay_backrest",
			mcp.WithDescription("Receive Backrest backup webhook"),
			mcp.WithNumber("data_added",
				mcp.Description("data_added"),
			),
			mcp.WithNumber("duration_ms",
				mcp.Description("duration_ms"),
			),
			mcp.WithString("error",
				mcp.Description("error"),
			),
			mcp.WithString("event",
				mcp.Description("event"),
			),
			mcp.WithNumber("files_changed",
				mcp.Description("files_changed"),
			),
			mcp.WithNumber("files_new",
				mcp.Description("files_new"),
			),
			mcp.WithString("plan",
				mcp.Description("plan"),
			),
			mcp.WithString("repo",
				mcp.Description("repo"),
			),
			mcp.WithString("snapshot_id",
				mcp.Description("snapshot_id"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayBackrest(ctx, req, relay)
		},
	)

	// relay_bazarr
	s.AddTool(
		mcp.NewTool("relay_bazarr",
			mcp.WithDescription("Receive Bazarr subtitle webhook"),
			mcp.WithString("message",
				mcp.Description("message"),
			),
			mcp.WithString("title",
				mcp.Description("title"),
			),
			mcp.WithString("type",
				mcp.Description("type"),
			),
			mcp.WithString("version",
				mcp.Description("version"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayBazarr(ctx, req, relay)
		},
	)

	// relay_changedetection
	s.AddTool(
		mcp.NewTool("relay_changedetection",
			mcp.WithDescription("Receive Changedetection.io webhook"),
			mcp.WithString("diff_url",
				mcp.Description("diff_url"),
			),
			mcp.WithString("preview_url",
				mcp.Description("preview_url"),
			),
			mcp.WithString("tag",
				mcp.Description("tag"),
			),
			mcp.WithString("timestamp",
				mcp.Description("timestamp"),
			),
			mcp.WithString("title",
				mcp.Description("title"),
			),
			mcp.WithString("triggered_text",
				mcp.Description("triggered_text"),
			),
			mcp.WithString("url",
				mcp.Description("url"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayChangedetection(ctx, req, relay)
		},
	)

	// relay_gatus
	s.AddTool(
		mcp.NewTool("relay_gatus",
			mcp.WithDescription("Receive Gatus health check webhook"),
			mcp.WithString("alert_description",
				mcp.Description("alert_description"),
			),
			mcp.WithString("endpoint_group",
				mcp.Description("endpoint_group"),
			),
			mcp.WithString("endpoint_name",
				mcp.Description("endpoint_name"),
			),
			mcp.WithString("endpoint_url",
				mcp.Description("endpoint_url"),
			),
			mcp.WithString("result_errors",
				mcp.Description("result_errors"),
			),
			mcp.WithString("status",
				mcp.Description("status"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayGatus(ctx, req, relay)
		},
	)

	// relay_grafana
	s.AddTool(
		mcp.NewTool("relay_grafana",
			mcp.WithDescription("Receive Grafana alert webhook. Pass the full JSON payload."),
			mcp.WithString("payload_json",
				mcp.Required(),
				mcp.Description("Full webhook JSON payload for grafana"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayGrafana(ctx, req, relay)
		},
	)

	// relay_jellyfin
	s.AddTool(
		mcp.NewTool("relay_jellyfin",
			mcp.WithDescription("Receive Jellyfin webhook. Pass the full JSON payload."),
			mcp.WithString("payload_json",
				mcp.Required(),
				mcp.Description("Full webhook JSON payload for jellyfin"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayJellyfin(ctx, req, relay)
		},
	)

	// relay_overseerr
	s.AddTool(
		mcp.NewTool("relay_overseerr",
			mcp.WithDescription("Receive Overseerr media request webhook. Pass the full JSON payload."),
			mcp.WithString("payload_json",
				mcp.Required(),
				mcp.Description("Full webhook JSON payload for overseerr"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayOverseerr(ctx, req, relay)
		},
	)

	// relay_paperless
	s.AddTool(
		mcp.NewTool("relay_paperless",
			mcp.WithDescription("Receive Paperless-ngx webhook"),
			mcp.WithString("correspondent",
				mcp.Description("correspondent"),
			),
			mcp.WithNumber("doc_id",
				mcp.Description("doc_id"),
			),
			mcp.WithString("doc_url",
				mcp.Description("doc_url"),
			),
			mcp.WithString("document_type",
				mcp.Description("document_type"),
			),
			mcp.WithString("event",
				mcp.Description("event"),
			),
			mcp.WithString("filename",
				mcp.Description("filename"),
			),
			mcp.WithString("tags",
				mcp.Description("tags"),
			),
			mcp.WithString("title",
				mcp.Description("title"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayPaperless(ctx, req, relay)
		},
	)

	// relay_prowlarr
	s.AddTool(
		mcp.NewTool("relay_prowlarr",
			mcp.WithDescription("Receive Prowlarr webhook. Pass the full JSON payload (eventType determines the shape)."),
			mcp.WithString("payload_json",
				mcp.Required(),
				mcp.Description("Full webhook JSON payload for prowlarr"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayProwlarr(ctx, req, relay)
		},
	)

	// relay_proxmox
	s.AddTool(
		mcp.NewTool("relay_proxmox",
			mcp.WithDescription("Receive Proxmox notification webhook"),
			mcp.WithString("hostname",
				mcp.Description("hostname"),
			),
			mcp.WithString("message",
				mcp.Description("message"),
			),
			mcp.WithString("severity",
				mcp.Description("severity"),
			),
			mcp.WithString("title",
				mcp.Description("title"),
			),
			mcp.WithString("type",
				mcp.Description("type"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayProxmox(ctx, req, relay)
		},
	)

	// relay_radarr
	s.AddTool(
		mcp.NewTool("relay_radarr",
			mcp.WithDescription("Receive Radarr webhook. Pass the full JSON payload (eventType determines the shape)."),
			mcp.WithString("payload_json",
				mcp.Required(),
				mcp.Description("Full webhook JSON payload for radarr"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayRadarr(ctx, req, relay)
		},
	)

	// relay_sonarr
	s.AddTool(
		mcp.NewTool("relay_sonarr",
			mcp.WithDescription("Receive Sonarr webhook. Pass the full JSON payload (eventType determines the shape)."),
			mcp.WithString("payload_json",
				mcp.Required(),
				mcp.Description("Full webhook JSON payload for sonarr"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelaySonarr(ctx, req, relay)
		},
	)

	// relay_unmanic
	s.AddTool(
		mcp.NewTool("relay_unmanic",
			mcp.WithDescription("Receive Unmanic task webhook"),
			mcp.WithString("message",
				mcp.Description("message"),
			),
			mcp.WithString("title",
				mcp.Description("title"),
			),
			mcp.WithString("type",
				mcp.Description("type"),
			),
			mcp.WithString("version",
				mcp.Description("version"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayUnmanic(ctx, req, relay)
		},
	)

	// relay_uptimekuma
	s.AddTool(
		mcp.NewTool("relay_uptimekuma",
			mcp.WithDescription("Receive Uptime Kuma webhook. Pass the full JSON payload."),
			mcp.WithString("payload_json",
				mcp.Required(),
				mcp.Description("Full webhook JSON payload for uptimekuma"),
			),
		),
		func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
			return handleRelayUptimekuma(ctx, req, relay)
		},
	)
}

func handleRelayArgocd(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	body := map[string]any{}
	if v := req.GetString("app", ""); v != "" {
		body["app"] = v
	}
	if v := req.GetString("event", ""); v != "" {
		body["event"] = v
	}
	if v := req.GetString("repo_url", ""); v != "" {
		body["repo_url"] = v
	}
	if v := req.GetString("revision", ""); v != "" {
		body["revision"] = v
	}
	raw, err := relay.PostWebhook(ctx, "argocd", body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayBackrest(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	body := map[string]any{}
	if v := req.GetFloat("data_added", math.NaN()); !math.IsNaN(v) {
		body["data_added"] = v
	}
	if v := req.GetFloat("duration_ms", math.NaN()); !math.IsNaN(v) {
		body["duration_ms"] = v
	}
	if v := req.GetString("error", ""); v != "" {
		body["error"] = v
	}
	if v := req.GetString("event", ""); v != "" {
		body["event"] = v
	}
	if v := req.GetFloat("files_changed", math.NaN()); !math.IsNaN(v) {
		body["files_changed"] = v
	}
	if v := req.GetFloat("files_new", math.NaN()); !math.IsNaN(v) {
		body["files_new"] = v
	}
	if v := req.GetString("plan", ""); v != "" {
		body["plan"] = v
	}
	if v := req.GetString("repo", ""); v != "" {
		body["repo"] = v
	}
	if v := req.GetString("snapshot_id", ""); v != "" {
		body["snapshot_id"] = v
	}
	raw, err := relay.PostWebhook(ctx, "backrest", body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayBazarr(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	body := map[string]any{}
	if v := req.GetString("message", ""); v != "" {
		body["message"] = v
	}
	if v := req.GetString("title", ""); v != "" {
		body["title"] = v
	}
	if v := req.GetString("type", ""); v != "" {
		body["type"] = v
	}
	if v := req.GetString("version", ""); v != "" {
		body["version"] = v
	}
	raw, err := relay.PostWebhook(ctx, "bazarr", body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayChangedetection(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	body := map[string]any{}
	if v := req.GetString("diff_url", ""); v != "" {
		body["diff_url"] = v
	}
	if v := req.GetString("preview_url", ""); v != "" {
		body["preview_url"] = v
	}
	if v := req.GetString("tag", ""); v != "" {
		body["tag"] = v
	}
	if v := req.GetString("timestamp", ""); v != "" {
		body["timestamp"] = v
	}
	if v := req.GetString("title", ""); v != "" {
		body["title"] = v
	}
	if v := req.GetString("triggered_text", ""); v != "" {
		body["triggered_text"] = v
	}
	if v := req.GetString("url", ""); v != "" {
		body["url"] = v
	}
	raw, err := relay.PostWebhook(ctx, "changedetection", body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayGatus(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	body := map[string]any{}
	if v := req.GetString("alert_description", ""); v != "" {
		body["alert_description"] = v
	}
	if v := req.GetString("endpoint_group", ""); v != "" {
		body["endpoint_group"] = v
	}
	if v := req.GetString("endpoint_name", ""); v != "" {
		body["endpoint_name"] = v
	}
	if v := req.GetString("endpoint_url", ""); v != "" {
		body["endpoint_url"] = v
	}
	if v := req.GetString("result_errors", ""); v != "" {
		body["result_errors"] = v
	}
	if v := req.GetString("status", ""); v != "" {
		body["status"] = v
	}
	raw, err := relay.PostWebhook(ctx, "gatus", body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayGrafana(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	payloadStr, err := req.RequireString("payload_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(payloadStr)) {
		return mcp.NewToolResultError("payload_json is not valid JSON"), nil
	}
	raw, err := relay.PostWebhook(ctx, "grafana", json.RawMessage(payloadStr))
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayJellyfin(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	payloadStr, err := req.RequireString("payload_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(payloadStr)) {
		return mcp.NewToolResultError("payload_json is not valid JSON"), nil
	}
	raw, err := relay.PostWebhook(ctx, "jellyfin", json.RawMessage(payloadStr))
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayOverseerr(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	payloadStr, err := req.RequireString("payload_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(payloadStr)) {
		return mcp.NewToolResultError("payload_json is not valid JSON"), nil
	}
	raw, err := relay.PostWebhook(ctx, "overseerr", json.RawMessage(payloadStr))
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayPaperless(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	body := map[string]any{}
	if v := req.GetString("correspondent", ""); v != "" {
		body["correspondent"] = v
	}
	if v := req.GetFloat("doc_id", math.NaN()); !math.IsNaN(v) {
		body["doc_id"] = v
	}
	if v := req.GetString("doc_url", ""); v != "" {
		body["doc_url"] = v
	}
	if v := req.GetString("document_type", ""); v != "" {
		body["document_type"] = v
	}
	if v := req.GetString("event", ""); v != "" {
		body["event"] = v
	}
	if v := req.GetString("filename", ""); v != "" {
		body["filename"] = v
	}
	if v := req.GetString("tags", ""); v != "" {
		body["tags"] = v
	}
	if v := req.GetString("title", ""); v != "" {
		body["title"] = v
	}
	raw, err := relay.PostWebhook(ctx, "paperless", body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayProwlarr(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	payloadStr, err := req.RequireString("payload_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(payloadStr)) {
		return mcp.NewToolResultError("payload_json is not valid JSON"), nil
	}
	raw, err := relay.PostWebhook(ctx, "prowlarr", json.RawMessage(payloadStr))
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayProxmox(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	body := map[string]any{}
	if v := req.GetString("hostname", ""); v != "" {
		body["hostname"] = v
	}
	if v := req.GetString("message", ""); v != "" {
		body["message"] = v
	}
	if v := req.GetString("severity", ""); v != "" {
		body["severity"] = v
	}
	if v := req.GetString("title", ""); v != "" {
		body["title"] = v
	}
	if v := req.GetString("type", ""); v != "" {
		body["type"] = v
	}
	raw, err := relay.PostWebhook(ctx, "proxmox", body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayRadarr(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	payloadStr, err := req.RequireString("payload_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(payloadStr)) {
		return mcp.NewToolResultError("payload_json is not valid JSON"), nil
	}
	raw, err := relay.PostWebhook(ctx, "radarr", json.RawMessage(payloadStr))
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelaySonarr(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	payloadStr, err := req.RequireString("payload_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(payloadStr)) {
		return mcp.NewToolResultError("payload_json is not valid JSON"), nil
	}
	raw, err := relay.PostWebhook(ctx, "sonarr", json.RawMessage(payloadStr))
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayUnmanic(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	body := map[string]any{}
	if v := req.GetString("message", ""); v != "" {
		body["message"] = v
	}
	if v := req.GetString("title", ""); v != "" {
		body["title"] = v
	}
	if v := req.GetString("type", ""); v != "" {
		body["type"] = v
	}
	if v := req.GetString("version", ""); v != "" {
		body["version"] = v
	}
	raw, err := relay.PostWebhook(ctx, "unmanic", body)
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}

func handleRelayUptimekuma(ctx context.Context, req mcp.CallToolRequest, relay *client.RelayClient) (*mcp.CallToolResult, error) {
	payloadStr, err := req.RequireString("payload_json")
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	if !json.Valid([]byte(payloadStr)) {
		return mcp.NewToolResultError("payload_json is not valid JSON"), nil
	}
	raw, err := relay.PostWebhook(ctx, "uptimekuma", json.RawMessage(payloadStr))
	if err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	}
	return mcp.NewToolResultText(string(raw)), nil
}
